const WALLET_ACTIONS_TYPES = {
  WALLET_IS_FETCHING: 'WALLET_IS_FETCHING',
  WALLET_ERROR: 'WALLET_ERROR',
  LOAD_WALLET_SUCCESS: 'LOAD_WALLET_SUCCESS',
  FETCH_CURRENCIES_SUCCESS: 'FETCH_CURRENCIES_SUCCESS',
  ADD_EXPENSE_SUCCESS: 'ADD_EXPENSE_SUCCESS',
  EDIT_EXPENSE_SUCCESS: 'ADD_EXPENSE_SUCCESS',
};

export default WALLET_ACTIONS_TYPES;
