const WALLET_ACTIONS_TYPES = {
  LOAD_WALLET: 'LOAD_WALLET',
  LOAD_WALLET_SUCCESS: 'LOAD_WALLET_SUCCESS',
  LOAD_WALLET_ERROR: 'LOAD_WALLET_ERROR',
  FETCH_CURRENCIES: 'FETCH_CURRENCIES',
  FETCH_CURRENCIES_SUCCESS: 'FETCH_CURRENCIES_SUCCESS',
  FETCH_CURRENCIES_ERROR: 'FETCH_CURRENCIES_ERROR',
};

export default WALLET_ACTIONS_TYPES;
